# Generated by Django 5.2.7 on 2025-10-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_adminaccessaudit'),
        ('complaints', '0006_adminaccessaudit'),
    ]

    operations = [
    ]
