# Generated by Copilot on 2025-10-22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_merge_0003_adminaccessaudit_0006_adminaccessaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='submitter_name',
            field=models.CharField(max_length=150, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitter_division',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitter_admission_no',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
    ]
