# Generated by Django 4.2.25 on 2025-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_submitter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcomplaint',
            name='submitter_admission_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='submitter_division',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='submitter_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
